"""change field user model

Revision ID: 1038989c3694
Revises: 699e2687d7f9
Create Date: 2022-07-12 17:49:06.784311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1038989c3694'
down_revision = '699e2687d7f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('usuario', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('usuario', 'username')
    # ### end Alembic commands ###
