"""teste alembic 2

Revision ID: 80af7d32b04d
Revises: 99c1a2ac04cc
Create Date: 2022-07-10 15:05:17.710771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af7d32b04d'
down_revision = '99c1a2ac04cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'date')
    # ### end Alembic commands ###
