"""TESTE PROD DB

Revision ID: 9460504ee216
Revises: 0621adec1e16
Create Date: 2022-07-13 16:49:47.688369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9460504ee216'
down_revision = '0621adec1e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
